<?php

namespace Database\Seeders;

use App\Models\CuerpoAcademico;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CuerpoAcademicoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        CuerpoAcademico::factory()->count(314)->sequence(

            ['nombre' => 'Desarrollo Sustentable, Sociedad y Ambiente', 'espacio_academico_id' => '9bc6bf2f-5fb9-4f49-8aa0-b2c7c960c60d'],
            ['nombre' => 'Desarrollo sociocultural', 'espacio_academico_id' => '9bc6bf2f-6b40-4bc9-a7b2-d26dc34daf2f'],
            ['nombre' => 'Heterogeneidad y equidad social', 'espacio_academico_id' => '9bc6bf2f-6b40-4bc9-a7b2-d26dc34daf2f'],
            ['nombre' => 'Desarrollo Social y Político en México y América Latina', 'espacio_academico_id' => '9bc6bf2f-7367-42de-ba87-c6f699a8301b'],
            ['nombre' => 'Procesos sociales contemporáneos', 'espacio_academico_id' => '9bc6bf2f-7367-42de-ba87-c6f699a8301b'],
            ['nombre' => 'Sociedades y culturas de América Latina', 'espacio_academico_id' => '9bc6bf2f-7367-42de-ba87-c6f699a8301b'],
            ['nombre' => 'Sociedades y culturas de América Latina', 'espacio_academico_id' => '9bc6bf2f-7367-42de-ba87-c6f699a8301b'],
            ['nombre' => 'Educación y sociedad', 'espacio_academico_id' => '9bc6bf2f-7851-461b-8450-76776d5f5685'],
            ['nombre' => 'Procesos Creativos, Aprendizaje y Psicoafectividad', 'espacio_academico_id' => '9bc6bf2f-7851-461b-8450-76776d5f5685'],
            ['nombre' => 'Universidad y Desarrollo Humano', 'espacio_academico_id' => '9bc6bf2f-7851-461b-8450-76776d5f5685'],
            ['nombre' => 'Desigualdad y vulnerabilidad demográfica', 'espacio_academico_id' => '9bc6bf2f-7d83-434d-b889-10ceb04e4f5f'],
            ['nombre' => 'Migración Interna e Internacional', 'espacio_academico_id' => '9bc6bf2f-7d83-434d-b889-10ceb04e4f5f'],
            ['nombre' => 'Biotecnología Animal', 'espacio_academico_id' => '9bc6bf2f-823f-47b8-9953-66206beaf89a'],
            ['nombre' => 'Ciencia Política y Administración Pública', 'espacio_academico_id' => '9bc6bf2f-823f-47b8-9953-66206beaf89a'],
            ['nombre' => 'Estudios Multidisciplinarios sobre Desarrollo Endógeno para la Sustentabilidad Territorial', 'espacio_academico_id' => '9bc6bf2f-823f-47b8-9953-66206beaf89a'],
            ['nombre' => 'Investigación aplicada en producción animal y ecodesarrollo territorial', 'espacio_academico_id' => '9bc6bf2f-823f-47b8-9953-66206beaf89a'],
            ['nombre' => 'Literatura, Lengua y Cultura de América Latina', 'espacio_academico_id' => '9bc6bf2f-823f-47b8-9953-66206beaf89a'],
            ['nombre' => 'Nutrición humana, educación y salud colectiva', 'espacio_academico_id' => '9bc6bf2f-823f-47b8-9953-66206beaf89a'],
            ['nombre' => 'Desarrollo de Software, Dispositivos y Sistemas Aplicados a la Innovación Tecnológica', 'espacio_academico_id' => '9bc6bf2f-878e-4ca2-815a-2a77591c4628'],
            ['nombre' => 'Psicobiología de la conducta y ciencias cognitivas', 'espacio_academico_id' => '9bc6bf2f-878e-4ca2-815a-2a77591c4628'],
            ['nombre' => 'Tendencias fiscales, financieras y de responsabilidad social en el siglo XXI', 'espacio_academico_id' => '9bc6bf2f-878e-4ca2-815a-2a77591c4628'],
            ['nombre' => 'Psicología y Sociedad Contemporánea', 'espacio_academico_id' => '9bc6bf2f-8c50-4f4a-9a2e-0ecd6536f6cd'],
            ['nombre' => 'Sociología organizacional y sustentabilidad', 'espacio_academico_id' => '9bc6bf2f-8c50-4f4a-9a2e-0ecd6536f6cd'],
            ['nombre' => 'TICs y Dispositivos Electrónicos', 'espacio_academico_id' => '9bc6bf2f-8c50-4f4a-9a2e-0ecd6536f6cd'],
            ['nombre' => 'Biopsicología, Salud y Sociedad', 'espacio_academico_id' => '9bc6bf2f-91e1-4418-817a-16f0d6b4deec'],
            ['nombre' => 'Comercio, economía y negocios internacionales para el desarrollo', 'espacio_academico_id' => '9bc6bf2f-91e1-4418-817a-16f0d6b4deec'],
            ['nombre' => 'Diseño e Implementación de Sistemas y Tecnologías Inteligentes', 'espacio_academico_id' => '9bc6bf2f-91e1-4418-817a-16f0d6b4deec'],
            ['nombre' => 'Género, sustentabilidad, salud y educación', 'espacio_academico_id' => '9bc6bf2f-91e1-4418-817a-16f0d6b4deec'],
            ['nombre' => 'Sustentabilidad y Planeación de Transporte Público', 'espacio_academico_id' => '9bc6bf2f-91e1-4418-817a-16f0d6b4deec'],
            ['nombre' => 'Desarrollo de los Factores Sociales en México', 'espacio_academico_id' => '9bc6bf2f-9674-4bff-b6ab-3f94cdbe3f16'],
            ['nombre' => 'Innovación tecnológica y sustentabilidad agropecuaria', 'espacio_academico_id' => '9bc6bf2f-9674-4bff-b6ab-3f94cdbe3f16'],
            ['nombre' => 'Sistemas de Producción Agropecuaria y Recursos Naturales', 'espacio_academico_id' => '9bc6bf2f-9674-4bff-b6ab-3f94cdbe3f16'],
            ['nombre' => 'Sistemas de Producción Agropecuaria y Recursos Naturales', 'espacio_academico_id' => '9bc6bf2f-9674-4bff-b6ab-3f94cdbe3f16'],
            ['nombre' => 'Análisis, Rescate y Aprovechamiento de Recursos Locales', 'espacio_academico_id' => '9bc6bf2f-9bc5-44ff-8077-10520e48b450'],
            ['nombre' => 'Conservación y Manejo de Recursos Bióticos y Culturales', 'espacio_academico_id' => '9bc6bf2f-9bc5-44ff-8077-10520e48b450'],
            ['nombre' => 'Estudios Regionales Multidisciplinarios', 'espacio_academico_id' => '9bc6bf2f-9bc5-44ff-8077-10520e48b450'],
            ['nombre' => 'Fisiología y protección vegetal sostenible', 'espacio_academico_id' => '9bc6bf2f-9bc5-44ff-8077-10520e48b450'],
            ['nombre' => 'Aplicaciones de sistemas inteligentes', 'espacio_academico_id' => '9bc6bf2f-a08b-4a16-b047-3ff1c889bda3'],
            ['nombre' => 'Computación e Informática Aplicada', 'espacio_academico_id' => '9bc6bf2f-a08b-4a16-b047-3ff1c889bda3'],
            ['nombre' => 'Desarrollo de software y tecnología', 'espacio_academico_id' => '9bc6bf2f-a08b-4a16-b047-3ff1c889bda3'],
            ['nombre' => 'Empresa, educación y tecnología', 'espacio_academico_id' => '9bc6bf2f-a08b-4a16-b047-3ff1c889bda3'],
            ['nombre' => 'Estudios Socioculturales del Turismo', 'espacio_academico_id' => '9bc6bf2f-a08b-4a16-b047-3ff1c889bda3'],
            ['nombre' => 'Los sectores productivos y el comercio internacional', 'espacio_academico_id' => '9bc6bf2f-a08b-4a16-b047-3ff1c889bda3'],
            ['nombre' => 'Nuevos Paradigmas Procesales en Materia Civil y Penal', 'espacio_academico_id' => '9bc6bf2f-a08b-4a16-b047-3ff1c889bda3'],
            ['nombre' => 'Política, Gobierno y Territorio', 'espacio_academico_id' => '9bc6bf2f-a08b-4a16-b047-3ff1c889bda3'],
            ['nombre' => 'Ciencias Avanzadas de la Salud', 'espacio_academico_id' => '9bc6bf2f-a5cf-40e7-b83b-4b0ec0e99511'],
            ['nombre' => 'Cómputo Aplicado', 'espacio_academico_id' => '9bc6bf2f-a5cf-40e7-b83b-4b0ec0e99511'],
            ['nombre' => 'Cómputo científico y sus aplicaciones', 'espacio_academico_id' => '9bc6bf2f-a5cf-40e7-b83b-4b0ec0e99511'],
            ['nombre' => 'Cómputo inteligente y sistemas', 'espacio_academico_id' => '9bc6bf2f-a5cf-40e7-b83b-4b0ec0e99511'],
            ['nombre' => 'Diseño Industrial', 'espacio_academico_id' => '9bc6bf2f-a5cf-40e7-b83b-4b0ec0e99511'],
            ['nombre' => 'Sistemas Complejos, Sustentabilidad e Innovación', 'espacio_academico_id' => '9bc6bf2f-a5cf-40e7-b83b-4b0ec0e99511'],
            ['nombre' => 'Administración pública y educación', 'espacio_academico_id' => '9bc6bf2f-aa96-413b-ac7f-27816f88c572'],
            ['nombre' => 'Complejidad social, desarrollo y tecnología', 'espacio_academico_id' => '9bc6bf2f-aa96-413b-ac7f-27816f88c572'],
            ['nombre' => 'Complejidad social, desarrollo y tecnología', 'espacio_academico_id' => '9bc6bf2f-aa96-413b-ac7f-27816f88c572'],
            ['nombre' => 'Economía Financiera', 'espacio_academico_id' => '9bc6bf2f-aa96-413b-ac7f-27816f88c572'],
            ['nombre' => 'Informática y tecnología en las organizaciones', 'espacio_academico_id' => '9bc6bf2f-aa96-413b-ac7f-27816f88c572'],
            ['nombre' => 'Ingeniería Industrial Avanzada', 'espacio_academico_id' => '9bc6bf2f-aa96-413b-ac7f-27816f88c572'],
            ['nombre' => 'Inteligencia Computacional', 'espacio_academico_id' => '9bc6bf2f-aa96-413b-ac7f-27816f88c572'],
            ['nombre' => 'Administración contable-financiera', 'espacio_academico_id' => '9bc6bf2f-c053-48ba-8368-776b04f7f9d9'],
            ['nombre' => 'Educación, Tecnología y Ciencias', 'espacio_academico_id' => '9bc6bf2f-c053-48ba-8368-776b04f7f9d9'],
            ['nombre' => 'Estudios ambientales, socioculturales, tecnológicos y políticas públicas', 'espacio_academico_id' => '9bc6bf2f-c053-48ba-8368-776b04f7f9d9'],
            ['nombre' => 'Investigación en computación', 'espacio_academico_id' => '9bc6bf2f-c053-48ba-8368-776b04f7f9d9'],
            ['nombre' => 'Actores Sujetos y Procesos Sociales ante la Modernización', 'espacio_academico_id' => '9bc6bf2f-d24e-43aa-87b0-0d47e3e86253'],
            ['nombre' => 'Ciencia del Cuidado, Salud y Educación', 'espacio_academico_id' => '9bc6bf2f-d24e-43aa-87b0-0d47e3e86253'],
            ['nombre' => 'Conocimiento, Transferencia y Emprendimiento', 'espacio_academico_id' => '9bc6bf2f-d24e-43aa-87b0-0d47e3e86253'],
            ['nombre' => 'Gestión de la Educación e Investigación Sustentable', 'espacio_academico_id' => '9bc6bf2f-d24e-43aa-87b0-0d47e3e86253'],
            ['nombre' => 'Gestión de la salud', 'espacio_academico_id' => '9bc6bf2f-d24e-43aa-87b0-0d47e3e86253'],
            ['nombre' => 'Tecnologías computacionales aplicadas', 'espacio_academico_id' => '9bc6bf2f-d24e-43aa-87b0-0d47e3e86253'],
            ['nombre' => 'Estudios interdisciplinarios sobre artes escénicas, visuales y literarias: Poética, género y cultura', 'espacio_academico_id' => '9bc6bf2f-e141-4686-b046-dc744deb7332'],
            ['nombre' => 'Conservación y Manejo de Recursos Naturales', 'espacio_academico_id' => '9bc6bf2f-eb19-45a2-af85-25d5390be1d6'],
            ['nombre' => 'Estudios Agroalimentarios', 'espacio_academico_id' => '9bc6bf2f-eb19-45a2-af85-25d5390be1d6'],
            ['nombre' => 'Género, migraciones y desigualdades', 'espacio_academico_id' => '9bc6bf2f-eb19-45a2-af85-25d5390be1d6'],
            ['nombre' => 'Procesos Sociales en el Medio Rural', 'espacio_academico_id' => '9bc6bf2f-eb19-45a2-af85-25d5390be1d6'],
            ['nombre' => 'Producción Animal Campesina', 'espacio_academico_id' => '9bc6bf2f-eb19-45a2-af85-25d5390be1d6'],
            ['nombre' => 'Sistemas ecológicos y sostenibilidad agroecológica en áreas de montaña', 'espacio_academico_id' => '9bc6bf2f-eb19-45a2-af85-25d5390be1d6'],
            ['nombre' => 'Bioética y Salud Mental', 'espacio_academico_id' => '9bc6bf2f-f4eb-435b-8e24-afdd8ad4fdf1'],
            ['nombre' => 'Calidad de vida y decrecimiento', 'espacio_academico_id' => '9bc6bf2f-f4eb-435b-8e24-afdd8ad4fdf1'],
            ['nombre' => 'Estudios de la Universidad', 'espacio_academico_id' => '9bc6bf2f-f4eb-435b-8e24-afdd8ad4fdf1'],
            ['nombre' => 'Estudios de la Universidad', 'espacio_academico_id' => '9bc6bf2f-f4eb-435b-8e24-afdd8ad4fdf1'],
            ['nombre' => 'Procesos Sociales y Prácticas Institucionales desde el Pensamiento Crítico', 'espacio_academico_id' => '9bc6bf2f-f4eb-435b-8e24-afdd8ad4fdf1'],
            ['nombre' => 'Procesos Sociales y Prácticas Institucionales desde el Pensamiento Crítico', 'espacio_academico_id' => '9bc6bf2f-f4eb-435b-8e24-afdd8ad4fdf1'],
            ['nombre' => 'Universidad, Humanidades y Sociedad', 'espacio_academico_id' => '9bc6bf2f-f4eb-435b-8e24-afdd8ad4fdf1'],
            ['nombre' => 'Gestión Integrada del Agua', 'espacio_academico_id' => '9bc6bf2f-fa71-4461-94b3-a60f1f74dffb'],
            ['nombre' => 'Hidrología', 'espacio_academico_id' => '9bc6bf2f-fa71-4461-94b3-a60f1f74dffb'],
            ['nombre' => 'Hidrología', 'espacio_academico_id' => '9bc6bf2f-fa71-4461-94b3-a60f1f74dffb'],
            ['nombre' => 'Hidrología', 'espacio_academico_id' => '9bc6bf2f-fa71-4461-94b3-a60f1f74dffb'],
            ['nombre' => 'Tecnodesarrollo en Ciencias del Agua', 'espacio_academico_id' => '9bc6bf2f-fa71-4461-94b3-a60f1f74dffb'],
            ['nombre' => 'Tecnodesarrollos a partir de residuos sólidos y líquidos', 'espacio_academico_id' => '9bc6bf2f-fa71-4461-94b3-a60f1f74dffb'],
            ['nombre' => 'Tratamiento de Aguas y Control de la Contaminación', 'espacio_academico_id' => '9bc6bf2f-fa71-4461-94b3-a60f1f74dffb'],
            ['nombre' => 'Tratamiento de Aguas y Control de la Contaminación', 'espacio_academico_id' => '9bc6bf2f-fa71-4461-94b3-a60f1f74dffb'],
            ['nombre' => 'Tratamiento de Aguas y Control de la Contaminación', 'espacio_academico_id' => '9bc6bf2f-fa71-4461-94b3-a60f1f74dffb'],
            ['nombre' => 'Tratamiento de Aguas y Control de la Contaminación', 'espacio_academico_id' => '9bc6bf2f-fa71-4461-94b3-a60f1f74dffb'],
            ['nombre' => 'Conociendo al Bachillerato', 'espacio_academico_id' => '9bc6bf2f-ff12-48e9-b26e-e44af90d47d2'],
            ['nombre' => 'Formación Integral del Bachiller', 'espacio_academico_id' => '9bc6bf2f-ff12-48e9-b26e-e44af90d47d2'],
            ['nombre' => 'Estudios sobre orientación educativa, tutoría e inclusión escolar', 'espacio_academico_id' => '9bc6bf30-0449-4c77-845f-2bcfbbc66ae1'],
            ['nombre' => 'Aprendizaje, Desarrollo Humano y Desarrollo social en el Nivel Medio Superior', 'espacio_academico_id' => '9bc6bf30-090e-437f-87ae-53598af946b7'],
            ['nombre' => 'TIC en el Nivel Medio Superior', 'espacio_academico_id' => '9bc6bf30-090e-437f-87ae-53598af946b7'],

            ['nombre' => 'El Proceso de Enseñanza-Aprendizaje y el Uso de TIC en el Nivel Medio Superior', 'espacio_academico_id' => '9bc6bf30-0e64-4916-938b-ebe2c3b53a6f'],
            ['nombre' => 'Innovación Educativa en la Enseñanza de las Ciencias en el Bachillerato Universitario', 'espacio_academico_id' => '9bc6bf30-133c-403c-be7f-9b56ad6bf609'],
            ['nombre' => 'Acción tutorial en el nivel medio superior', 'espacio_academico_id' => '9bc6bf30-1876-4d7c-a9dd-fa4a6778082e'],
            ['nombre' => 'Diversidad académica en el nivel medio superior', 'espacio_academico_id' => '9bc6bf30-1876-4d7c-a9dd-fa4a6778082e'],
            ['nombre' => 'Ciencia, Humanismo y Educación con apoyo de inteligencia artificial en el Nivel Medio Superior', 'espacio_academico_id' => '9bc6bf30-1d35-4bef-ad3b-9f4c1c682473'],
            ['nombre' => 'Estrategias de Aprendizaje y Desarrollo Humano para elevar el Rendimiento Académico en el Nivel Medio Superior', 'espacio_academico_id' => '9bc6bf30-1d35-4bef-ad3b-9f4c1c682473'],
            ['nombre' => 'Mediación  y Conciliación  de conflictos  en el Nivel Medio Superior', 'espacio_academico_id' => '9bc6bf30-1d35-4bef-ad3b-9f4c1c682473'],
            ['nombre' => 'Las Profesiones y su Internacionalización en el Siglo XXI', 'espacio_academico_id' => '9bc6bf30-2286-43b9-8d73-40832072a850'],
            ['nombre' => 'Regulación, emprendimiento, movilidad y sostenibilidad para el desarrollo humano y crecimiento económico regional', 'espacio_academico_id' => '9bc6bf30-2286-43b9-8d73-40832072a850'],
            ['nombre' => 'Factores educativos, psicológicos y administrativos del desarrollo humano', 'espacio_academico_id' => '9bc6bf30-275f-43a9-abc5-978c0d6d8dbf'],
            ['nombre' => 'Ahorro de Energía en los Procesos de Manufactura', 'espacio_academico_id' => '9bc6bf30-2ccd-45dd-9288-a00d60fda072'],
            ['nombre' => 'Diseño de Sistemas', 'espacio_academico_id' => '9bc6bf30-2ccd-45dd-9288-a00d60fda072'],
            ['nombre' => 'Economía de datos en Educación y Diseño', 'espacio_academico_id' => '9bc6bf30-2ccd-45dd-9288-a00d60fda072'],
            ['nombre' => 'Sistemas Mecatrónicos y Computacionales Aplicados', 'espacio_academico_id' => '9bc6bf30-2ccd-45dd-9288-a00d60fda072'],
            ['nombre' => 'Tecnologías de la Información y Comunicaciones Aplicadas', 'espacio_academico_id' => '9bc6bf30-2ccd-45dd-9288-a00d60fda072'],
            ['nombre' => 'Análisis de la cultura y procesos socioculturales', 'espacio_academico_id' => '9bc6bf30-316a-45ed-9be7-19e540b81078'],
            ['nombre' => 'Etnografía y sistemas culturales', 'espacio_academico_id' => '9bc6bf30-316a-45ed-9be7-19e540b81078'],
            ['nombre' => 'Manifestaciones y diversidades de la cultura', 'espacio_academico_id' => '9bc6bf30-316a-45ed-9be7-19e540b81078'],
            ['nombre' => 'Patrones culturales de las relaciones sociales', 'espacio_academico_id' => '9bc6bf30-316a-45ed-9be7-19e540b81078'],
            ['nombre' => 'Contexto sociocultural del diseño', 'espacio_academico_id' => '9bc6bf30-362c-4599-9f10-e0dfd04d79d2'],
            ['nombre' => 'Diseño y Desarrollo Social', 'espacio_academico_id' => '9bc6bf30-362c-4599-9f10-e0dfd04d79d2'],
            ['nombre' => 'Diseño, territorio e inclusión', 'espacio_academico_id' => '9bc6bf30-362c-4599-9f10-e0dfd04d79d2'],
            ['nombre' => 'Diseño, territorio e inclusión', 'espacio_academico_id' => '9bc6bf30-362c-4599-9f10-e0dfd04d79d2'],
            ['nombre' => 'Estudios Urbanos y Arquitectónicos', 'espacio_academico_id' => '9bc6bf30-362c-4599-9f10-e0dfd04d79d2'],
            ['nombre' => 'Gestión y evaluación de objetos de diseño', 'espacio_academico_id' => '9bc6bf30-362c-4599-9f10-e0dfd04d79d2'],
            ['nombre' => 'Habitabilidad y Movilidad Urbana', 'espacio_academico_id' => '9bc6bf30-362c-4599-9f10-e0dfd04d79d2'],
            ['nombre' => 'Patrimonio, Ambiente y Tecnología', 'espacio_academico_id' => '9bc6bf30-362c-4599-9f10-e0dfd04d79d2'],
            ['nombre' => 'Patrimonio, Ambiente y Tecnología', 'espacio_academico_id' => '9bc6bf30-362c-4599-9f10-e0dfd04d79d2'],
            ['nombre' => 'Sostenibilidad y Desarrollo Estratégico del Diseño', 'espacio_academico_id' => '9bc6bf30-362c-4599-9f10-e0dfd04d79d2'],
            ['nombre' => 'Sostenibilidad y Desarrollo Estratégico del Diseño', 'espacio_academico_id' => '9bc6bf30-362c-4599-9f10-e0dfd04d79d2'],
            ['nombre' => 'Sostenibilidad y Desarrollo Estratégico del Diseño', 'espacio_academico_id' => '9bc6bf30-362c-4599-9f10-e0dfd04d79d2'],
            ['nombre' => 'Tecnologías para el diseño', 'espacio_academico_id' => '9bc6bf30-362c-4599-9f10-e0dfd04d79d2'],
            ['nombre' => 'Arte como Conocimiento', 'espacio_academico_id' => '9bc6bf30-3bc0-46a4-8156-6c039e6893ed'],
            ['nombre' => 'Episteme y visualidad contemporánea', 'espacio_academico_id' => '9bc6bf30-3bc0-46a4-8156-6c039e6893ed'],
            ['nombre' => 'Biología Aplicada', 'espacio_academico_id' => '9bc6bf30-436e-48d0-a848-bede3797c3cd'],
            ['nombre' => 'Biología y Biotecnología de Recursos Naturales', 'espacio_academico_id' => '9bc6bf30-436e-48d0-a848-bede3797c3cd'],
            ['nombre' => 'Ecogeografía e Interacciones Biológicas', 'espacio_academico_id' => '9bc6bf30-436e-48d0-a848-bede3797c3cd'],
            ['nombre' => 'Ecología, Evolución y Conservación de Vertebrados', 'espacio_academico_id' => '9bc6bf30-436e-48d0-a848-bede3797c3cd'],
            ['nombre' => 'Edafología y Ambiente', 'espacio_academico_id' => '9bc6bf30-436e-48d0-a848-bede3797c3cd'],
            ['nombre' => 'Física de sistemas en Femto y nano escalas', 'espacio_academico_id' => '9bc6bf30-436e-48d0-a848-bede3797c3cd'],
            ['nombre' => 'Física de sistemas en Femto y nano escalas', 'espacio_academico_id' => '9bc6bf30-436e-48d0-a848-bede3797c3cd'],
            ['nombre' => 'Física Estadística', 'espacio_academico_id' => '9bc6bf30-436e-48d0-a848-bede3797c3cd'],
            ['nombre' => 'Física Estadística', 'espacio_academico_id' => '9bc6bf30-436e-48d0-a848-bede3797c3cd'],
            ['nombre' => 'Interacción de Radiación con Materia', 'espacio_academico_id' => '9bc6bf30-436e-48d0-a848-bede3797c3cd'],
            ['nombre' => 'Procesos Biotecnológicos', 'espacio_academico_id' => '9bc6bf30-436e-48d0-a848-bede3797c3cd'],
            ['nombre' => 'Topología General e Hiperespacios de Continuos', 'espacio_academico_id' => '9bc6bf30-436e-48d0-a848-bede3797c3cd'],
            ['nombre' => 'Agroecología y Biofertilizantes', 'espacio_academico_id' => ''],
            ['nombre' => 'Ciencia y tecnología de los alimentos', 'espacio_academico_id' => ''],
            ['nombre' => 'Cultivos Básicos y Hortícolas', 'espacio_academico_id' => ''],
            ['nombre' => 'Cultivos Básicos y Hortícolas', 'espacio_academico_id' => ''],
            ['nombre' => 'Cultivos hortícolas y de uso industrial', 'espacio_academico_id' => ''],
            ['nombre' => 'Cultivos hortícolas y de uso industrial', 'espacio_academico_id' => ''],
            ['nombre' => 'Cultivos hortícolas y de uso industrial', 'espacio_academico_id' => ''],
            ['nombre' => 'Educación agropecuaria y desarrollo rural', 'espacio_academico_id' => ''],
            ['nombre' => 'Estudio y aprovechamiento de recursos fitogenéticos de México', 'espacio_academico_id' => ''],
            ['nombre' => 'Manejo Sustentable y Calidad en Productos Agropecuarios', 'espacio_academico_id' => ''],
            ['nombre' => 'Mejoramiento Genético y Sanidad Vegetal', 'espacio_academico_id' => ''],
            ['nombre' => 'Mejoramiento Genético y Sanidad Vegetal', 'espacio_academico_id' => ''],
            ['nombre' => 'Actores y Procesos Académicos de la Educación', 'espacio_academico_id' => ''],
            ['nombre' => 'Clínica y Familia', 'espacio_academico_id' => ''],
            ['nombre' => 'Clínica y Familia', 'espacio_academico_id' => ''],
            ['nombre' => 'Cultura y Personalidad'],
            ['nombre' => 'Cultura y sujeto'],
            ['nombre' => 'Educación e Innovación'],
            ['nombre' => 'Investigación e intervención multidisciplinaria en los problemas sociales contemporáneos'],
            ['nombre' => 'Investigación e intervención multidisciplinaria en los problemas sociales contemporáneos'],
            ['nombre' => 'Psicología y Educación'],
            ['nombre' => 'Socialización, Juventud y Estilos de Crianza'],
            ['nombre' => 'Teoría, Historia y Políticas  de la educación'],
            ['nombre' => 'Vulnerabilidad, Educación y Sustentabilidad'],
            ['nombre' => 'Actores Sociales, Participación y Desarrollo Alternativo'],
            ['nombre' => 'Administración Pública, Política y Gobierno'],
            ['nombre' => 'Ciudadanía, Exclusión y Políticas Públicas en México y América Latina'],
            ['nombre' => 'Difusión y Divulgación de la Ciencia'],
            ['nombre' => 'Estudios interdisciplinarios para la paz y del desarrollo'],
            ['nombre' => 'Estudios Sociales de la Tecnociencia'],
            ['nombre' => 'Estudios Sociales de la Tecnociencia'],
            ['nombre' => 'Género, Espacio y Políticas Públicas'],
            ['nombre' => 'Instituciones y espacios de participación en México y América Latina'],
            ['nombre' => 'Narrativas culturales: medios, periodismo y comunicación institucional'],
            ['nombre' => 'Narrativas culturales: medios, periodismo y comunicación institucional'],
            ['nombre' => 'Narrativas culturales: medios, periodismo y comunicación institucional'],
            ['nombre' => 'Organización Social y Vida Cotidiana'],
            ['nombre' => 'Partidos, Procesos Electorales y Participación Política'],
            ['nombre' => 'Procesos y Territorios Sociales'],
            ['nombre' => 'Sociotecnología, gobierno y comunicación'],
            ['nombre' => 'Sociotecnología, gobierno y comunicación'],
            ['nombre' => 'Administración de las Organizaciones Educativas'],
            ['nombre' => 'Administración de las Organizaciones Educativas'],
            ['nombre' => 'Economía del Conocimiento y de la Organización'],
            ['nombre' => 'Educación y Gestión Organizacional: Emprendimiento, Marketing y TIC'],
            ['nombre' => 'Educación: docencia, investigación y gestión de recursos innovadores'],
            ['nombre' => 'Finanzas Tecnológicas'],
            ['nombre' => 'Gestión del Capital Intelectual'],
            ['nombre' => 'Gestión del Capital Intelectual'],
            ['nombre' => 'Productividad Organizacional'],
            ['nombre' => 'Productividad Organizacional'],
            ['nombre' => 'Derecho, Sociedad y Cultura'],
            ['nombre' => 'Estudios Constitucionales'],
            ['nombre' => 'Estudios Constitucionales'],
            ['nombre' => 'Estudios en derecho parlamentario'],
            ['nombre' => 'Estudios en Derecho Social, Procesos Sociales y Políticos'],
            ['nombre' => 'Estudios en derechos humanos y sus garantías'],
            ['nombre' => 'Estudios Gubernamentales'],
            ['nombre' => 'Estudios jurídicos de género, derechos humanos y de la sociedad'],
            ['nombre' => 'Estudios sobre oratoria, discurso jurídico y educación'],
            ['nombre' => 'Género, Derecho, Sociedad y Gobierno'],
            ['nombre' => 'Justicia Alternativa y Justicia Cotidiana'],
            ['nombre' => 'Justicia penal y buen gobierno'],
            ['nombre' => 'Análisis Económico de las Regiones, Sectores y la Globalidad en el Contexto Multicultural'],
            ['nombre' => 'Crecimiento, empleo y competitividad'],
            ['nombre' => 'Desarrollo Económico, Social y Regional'],
            ['nombre' => 'Economía de los Sectores Productivos e Institucionales'],
            ['nombre' => 'Economía del Bienestar'],
            ['nombre' => 'Economía financiera e internacional'],
            ['nombre' => 'Economía, Educación y Sustentabilidad'],
            ['nombre' => 'Estudios Económicos, Sociales y Actuariales'],
            ['nombre' => 'Cuidado Profesional de Enfermería'],
            ['nombre' => 'Cuidado y salud ambiental'],
            ['nombre' => 'Ejercicio en Enfermería'],
            ['nombre' => 'Enfermería y Cuidado de la Salud'],
            ['nombre' => 'Gerociencia y curso vital humano'],
            ['nombre' => 'Promoción y Educación para Salud'],
            ['nombre' => 'Salud, envejecimiento y educación'],
            ['nombre' => 'Análisis Geográfico Regional'],
            ['nombre' => 'Cuerpo Académico en Investigación Educativa'],
            ['nombre' => 'Cuerpo Académico en Investigación Educativa'],
            ['nombre' => 'Geografía, Ordenación y Gestión Sustentable del Territorio'],
            ['nombre' => 'Geoinformática y Ciencia de Datos Geoespaciales'],
            ['nombre' => 'Geotecnologías, ambiente y sociedades resilientes'],
            ['nombre' => 'Procesos Socio-económicos y Espaciales'],
            ['nombre' => 'Diálogos desde la Literatura'],
            ['nombre' => 'El Poder en México. Ayer y Hoy'],
            ['nombre' => 'Estudios Históricos de las Instituciones'],
            ['nombre' => 'Filosofía del mito, religión, literatura, educación desde una perspectiva ética'],
            ['nombre' => 'Historia y Crítica de la Literatura Hispanoamericana Contemporánea (Siglos XX, XXI)'],
            ['nombre' => 'Historia y crítica del arte y la cultura'],
            ['nombre' => 'Historia y Cultura'],
            ['nombre' => 'Historia: Educación, inclusión y fuentes'],
            ['nombre' => 'Literatura y Pensamiento Crítico'],
            ['nombre' => 'Pensamiento contemporáneo: Ser, Conocer, Hacer'],
            ['nombre' => 'Pensamiento contemporáneo: Ser, Conocer, Hacer'],
            ['nombre' => 'Sociedad del Conocimiento'],
            ['nombre' => 'Comportamiento Estructural'],
            ['nombre' => 'Dinámica de Sistemas y Control'],
            ['nombre' => 'Evaluación del riesgo y la confiabilidad estructural para sistemas y obras de ingeniería'],
            ['nombre' => 'Modelación de la Cadena de Suministro y Sistemas de Transporte'],
            ['nombre' => 'Movilidad y Transporte'],
            ['nombre' => 'Sistemas Computacionales'],
            ['nombre' => 'Sistemas Energéticos'],
            ['nombre' => 'Sistemas informáticos y electrónicos'],
            ['nombre' => 'Estudios en Lingüística y Docencia'],
            ['nombre' => 'Estudios en Lingüística y Docencia'],
            ['nombre' => 'Estudios en Literatura, Traducción y Cultura'],
            ['nombre' => 'Estudios sobre educación y lenguas'],
            ['nombre' => 'Estudios sobre educación y lenguas'],
            ['nombre' => 'Investigación Educativa en Lenguas'],
            ['nombre' => 'Biología Molecular'],
            ['nombre' => 'Clínica Médica'],
            ['nombre' => 'Educación, Salud y Ambiente: Hermenéutica como método interdisciplinario'],
            ['nombre' => 'Educación, Salud y Ambiente: Hermenéutica como método interdisciplinario'],
            ['nombre' => 'Física Médica'],
            ['nombre' => 'Ingeniería en sistemas biomédicos'],
            ['nombre' => 'Investigación traslacional e innovación en educación y salud'],
            ['nombre' => 'Medicina de la actividad física y el deporte'],
            ['nombre' => 'Medicina y Hermenéutica'],
            ['nombre' => 'Neurociencias'],
            ['nombre' => 'Nutrición y Salud'],
            ['nombre' => 'Pervivencia en Ciencias de la Salud'],
            ['nombre' => 'Salud Ambiental '],
            ['nombre' => 'Biotecnología Aplicada, Enfermedades Emergentes y Zoonosis'],
            ['nombre' => 'Biotecnología de nutrición y salud en ganadería'],
            ['nombre' => 'Ciencia e Innovación Tecnológica Pecuaria'],
            ['nombre' => 'Epidemiología y Salud Pública Veterinaria'],
            ['nombre' => 'Medicina y Cirugía Animal'],
            ['nombre' => 'Patogénesis Microbiana Veterinaria'],
            ['nombre' => 'Producción Animal'],
            ['nombre' => 'Reproducción animal'],
            ['nombre' => 'Salud Animal'],
            ['nombre' => 'Educación y Salud'],
            ['nombre' => 'Investigación Educativa en Odontología'],
            ['nombre' => 'Investigación Educativa en Odontología'],
            ['nombre' => 'Investigación odontológica multidisciplinaria'],
            ['nombre' => 'Salud - Enfermedad Bucal'],
            ['nombre' => 'Salud-Enfermedad Pulpar y Periradicular'],
            ['nombre' => 'Análisis e Interpretación de la Espacialidad en el Ámbito Urbano Metropolitano'],
            ['nombre' => 'Desarrollo, Ambiente y Procesos de Configuración Territorial'],
            ['nombre' => 'Estudios Territoriales y Ambientales'],
            ['nombre' => 'Planeación, Urbanismo y Medio Ambiente'],
            ['nombre' => 'Procesos territoriales, ambientales y sociales en el ámbito metapolitano y multiterritorial'],
            ['nombre' => 'Procesos Urbanos y Sociales'],
            ['nombre' => 'Relaciones Metrópoli-Ambiente'],
            ['nombre' => 'Ciencia de Materiales'],
            ['nombre' => 'Ciencias Alimentarias y Ambientales'],
            ['nombre' => 'Ciencias Farmacéuticas'],
            ['nombre' => 'Farmacología y Toxicología'],
            ['nombre' => 'Gestión Sustentable y Desarrollo Innovador'],
            ['nombre' => 'Ingeniería Química'],
            ['nombre' => 'Ingeniería Química'],
            ['nombre' => 'Investigación Biomédica'],
            ['nombre' => 'Nanomateriales'],
            ['nombre' => 'Petroquímica y Energía Sustentable'],
            ['nombre' => 'Química Ambiental'],
            ['nombre' => 'Química de alimentos y sus aplicaciones'],
            ['nombre' => 'Química de Coordinación'],
            ['nombre' => 'Química de Coordinación'],
            ['nombre' => 'Química Orgánica'],
            ['nombre' => 'Salud del Universitario'],
            ['nombre' => 'Síntesis, catálisis y modelado molecular'],
            ['nombre' => 'Alimentos, Cultura y Sociedad'],
            ['nombre' => 'Competitividad y sustentabilidad de las organizaciones turísticas y gastronómicas'],
            ['nombre' => 'Estudios sociales y educativos en turismo y gastronomía'],
            ['nombre' => 'Estudios sociales y educativos en turismo y gastronomía'],
            ['nombre' => 'Estudios Turísticos'],
            ['nombre' => 'Estudios Turísticos'],
            ['nombre' => 'Turismo, Cultura y Patrimonio'],
            ['nombre' => 'Turismo, Desarrollo y Sustentabilidad'],

        )->create();
    }
}
